### ISSUE TITLE
Settings to fully use a standard 104-key keyboard

### ISSUE THREAD

**Issue by noyannus** [acristoffers/kwin-rectangle#10]
This is a set of keys to fully use a standard 104-key keyboard, but leaving the arrow keys alone. 

Not meant to only add where the KWin settings don't have an option. It's a lower cognitive load to have a consistent scheme, and it is easier to set up if all is in one place.

Feel free to use in any way you see useful.

---

The modifiers follow some basic rules: `Meta` to position and resize, `meta + ctrl` to move, both `+ alt` for additional options. `Shift` to add the rarely used options.

`meta`  — position and resize to halves, quarters, sixths, and to maxi-/minimize
`meta + alt` — position and resize to thirds, two-thirds, and ninths
`meta + ctrl`	— move, keeping width and height
`meta + ctrl + alt` — maximize in one dimension (ctrl for move because "move center of window") 
`meta + ctrl + shift` — maximize in one dimension, exotic options

The key clusters were chosen because their outline serves as mnemonic for the screen divisions, and because the hand can target them without the need to look closely. Arrow keys are not used.

`prtscrn` `  scrllk  ` `  break  ` would be nice for thirds, and numpad's `   =   ` `   (   ` `   )   ` ` backsp ` for fourths, but unfortunately `prtscrn` interferes with the established Capture Screen of Spectacle, and numpad's `   =   ` `   (   ` `   )   ` do not work with meta (at least on a Microsoft Natuarl 4000) (is this fixable?). Therefore we'll resort to `meta + alt` and use the keys below.

Notation below is like this:
```
action or position
	modifier key(s)
		+ non-modifier key (list of options)
```

```
POSITION AND SIZE

halves, at screen border
	`meta`
		+ numpad numbers `8`, `6`, `2`, `4`

halves, centered	# not set, can be done in two steps (see below, CENTER)
	~,  all directions (corner quarter => center)
	~,  horizontal (top or bottom half => center)
	~,  vertical (left or right half => center)

fourths, left to right (portrait orientation)
	`meta`
		+ `numlock`  `/`  `x`  `-`    #   !!! `meta + numlock` toggles number lock. Can this be blocked?

quarters in screen corners
	`meta`
		+ numpad number `7`, `9`, `3`, `1` 

quarter centered  #	not set, can be done in two steps (below)
		(any corner quarter => center)

ninths
	`meta + alt`
		+ numpad `1` thru `9`

sixths, upper row
	`meta`
		+ `ins`, `home`, `pgup`

sixths, lower row
	`meta`
		+ `del`, `end`, ` pgdwn`

thirds, left to right (portrait orientation)
	`meta + alt`
		+ `ins`, `home`, `pgup`

two-thirds, left to right (portrait orientation)
	`meta + alt`
		+ `del`, `end`, `pgdwn`

-----------
MAXIMIZE/MINIMIZE

maximize
	`meta`
		+ numpad `enter`

almost maximize
	`meta`
		+ numpad `period` or `comma`

maximize height
	`meta + ctrl + alt`
		+ numpad `4`   # a bit arbitrary...

maximize width
	`meta + ctrl + alt`
		+ numpad `8`   # a bit arbitrary...

minimize
	`meta`
		+ numpad `0`

-----
NEW IDEAS

maximize upward only
	`meta + ctrl + shift` 
		+ numpad `8`
maximize downward only
	`meta + ctrl + shift` 
		+ numpad `2`
maximize to left only
	`meta + ctrl + shift` 
		+ numpad `4`
maximize to right only
	`meta + ctrl + shift` 
		+ numpad `6`

---------
CENTERING

Getting centered halves, thirds, two-thirds, quarters, sixths can be a two step procedure

	1. set to desired size, anywhere on screen (this includes arbitrary mouse drag sizes)
	2. center with `meta + ctrl + numpad 5` (keeping size)

This is the best option, imo. Centering is not a very frequent activity. It mostly happens for new windows, where it can be done with a window rule. And it trumps fiddling with hard to remember modifier combinations with numpad `5`, or, worse, different non-modifiers.

-------
MOVE

move
	`meta + ctrl`
		+ numpad `1` .. `4`, `6` .. `9` in the according direction
		+ numpad `5` to center (as above)
```

**Comment by acristoffers** [comment]
Oof, this one poses a problem: the shortcuts we have now is to keep parity with [Rectangle](https://rectangleapp.com), so making it totally different is not desirable, specially since I still use macOS at work, so I have the same set of shortcuts in both macOS and Plasma. Changing all shortcuts to make more sense in Plasma would break the easy transition for people coming from macOS and would also break the parity, making people who has to use both OS (i.e.: me) have to deal with two sets of bindings. Also, even though the use of the numpad may free up keys for other things, not everyone has a numpad. My external keyboard at home doesn't and most notebook keyboards don't either, so almost everyone on a notebook would have a "broken" set of shortcuts out of the box.

What I'll do is take a look to see if it's possible to unregister shortcuts and to run code from the settings page. This way I can provide a setting to chose between different presets, which would make it easy to switch between Rectangle, tankless and full-keyboard presets.

**Comment by acristoffers** [comment]
If you are aware of other kwin plugins which have buttons in their settings pane, feel free to link them here. KWin's docs are a mess, so basically I have to find other people who did things close to what I'll have to do.

**Comment by noyannus** [comment]
I am not aware of any plugin with buttons in the settings pane either, sorry.

But there's another way. Changing a fundamental set of shortcuts is a one-time operation on a new install, not something that needs to be done regularly. You could task the user to install pre-sets in the form of text files that get copied into the plasma settings. Because that circumvents Plasma's check for conflicting shortcuts such checks would have to be done manually.

In `~/.config/kglobalshortcutsrc`, section `[kwin]`, your entries are the lines beginning with `Rectangle: `. (A good place to check naming scheme consistency, btw.). You can ex/import the settings from system settings.

As an example, my Rectangle settings are at the moment these:
```
Rectangle: Almost Maximized=Meta+Num+\\,,none,Rectangle: Almost Maximized
Rectangle: Center=Meta+Ctrl+Num+5,none,Rectangle: Center
Rectangle: Centered Quarter=none,none,Rectangle: Centered Quarter
Rectangle: Fourth: First=Meta+NumLock,none,Rectangle: Fourth: First
Rectangle: Fourth: Fourth=Meta+Num+-,none,Rectangle: Fourth: Fourth
Rectangle: Fourth: Second=Meta+Num+/,none,Rectangle: Fourth: Second
Rectangle: Fourth: Third=Meta+Num+*,none,Rectangle: Fourth: Third
Rectangle: Halves: Bottom=Meta+Num+2,none,Rectangle: Halves: Bottom
Rectangle: Halves: Center=none,none,Rectangle: Halves: Center
Rectangle: Halves: Center (Horizontal)=none,none,Rectangle: Halves: Center (Horizontal)
Rectangle: Halves: Center (Vertical)=none,none,Rectangle: Halves: Center (Vertical)
Rectangle: Halves: Left=Meta+Num+4,none,Rectangle: Halves: Left
Rectangle: Halves: Right=Meta+Num+6,none,Rectangle: Halves: Right
Rectangle: Halves: Top=Meta+Num+8,none,Rectangle: Halves: Top
Rectangle: Maximize Height=Meta+Ctrl+Alt+Num+8,none,Rectangle: Maximize Height
Rectangle: Maximize Width=Meta+Ctrl+Alt+Num+4,none,Rectangle: Maximize Width
Rectangle: Maximized=Meta+Num+Enter,none,Rectangle: Maximized
Rectangle: Move: Bottom=Meta+Ctrl+Num+2,none,Rectangle: Move: Bottom
Rectangle: Move: Bottom Left=Meta+Ctrl+Num+1,none,Rectangle: Move: Bottom Left
Rectangle: Move: Bottom Right=Meta+Ctrl+Num+3,none,Rectangle: Move: Bottom Right
Rectangle: Move: Left=Meta+Ctrl+Num+4,none,Rectangle: Move: Left
Rectangle: Move: Right=Meta+Ctrl+Num+6,none,Rectangle: Move: Right
Rectangle: Move: Top=Meta+Ctrl+Num+8,none,Rectangle: Move: Top
Rectangle: Move: Top Left=Meta+Ctrl+Num+7,none,Rectangle: Move: Top Left
Rectangle: Move: Top Right=Meta+Ctrl+Num+9,none,Rectangle: Move: Top Right
Rectangle: Ninth: Bottom Center=Meta+Alt+Num+2,none,Rectangle: Ninth: Bottom Center
Rectangle: Ninth: Bottom Left=Meta+Alt+Num+1,none,Rectangle: Ninth: Bottom Left
Rectangle: Ninth: Bottom Right=Meta+Alt+Num+3,none,Rectangle: Ninth: Bottom Right
Rectangle: Ninth: Middle Center=Meta+Alt+Num+5,none,Rectangle: Ninth: Middle Center
Rectangle: Ninth: Middle Left=Meta+Alt+Num+4,none,Rectangle: Ninth: Middle Left
Rectangle: Ninth: Middle Right=Meta+Alt+Num+6,none,Rectangle: Ninth: Middle Right
Rectangle: Ninth: Top Center=Meta+Alt+Num+8,none,Rectangle: Ninth: Top Center
Rectangle: Ninth: Top Left=Meta+Alt+Num+7,none,Rectangle: Ninth: Top Left
Rectangle: Ninth: Top Right=Meta+Alt+Num+9,none,Rectangle: Ninth: Top Right
Rectangle: Quarter: Bottom Left=Meta+Num+1,none,Rectangle: Quarter: Bottom Left
Rectangle: Quarter: Bottom Right=Meta+Num+3,none,Rectangle: Quarter: Bottom Right
Rectangle: Quarter: Top Left=Meta+Num+7,none,Rectangle: Quarter: Top Left
Rectangle: Quarter: Top Right=Meta+Num+9,none,Rectangle: Quarter: Top Right
Rectangle: Sixth: Bottom Center=Meta+End,none,Rectangle: Sixth: Bottom Center
Rectangle: Sixth: Bottom Left=Meta+Del,none,Rectangle: Sixth: Bottom Left
Rectangle: Sixth: Bottom Right=Meta+PgDown,none,Rectangle: Sixth: Bottom Right
Rectangle: Sixth: Top Center=Meta+Home,none,Rectangle: Sixth: Top Center
Rectangle: Sixth: Top Left=Meta+Ins,none,Rectangle: Sixth: Top Left
Rectangle: Sixth: Top Right=Meta+PgUp,none,Rectangle: Sixth: Top Right
Rectangle: Thirds: First=Meta+Alt+Ins,none,Rectangle: Thirds: First
Rectangle: Thirds: Second=Meta+Alt+Home,none,Rectangle: Thirds: Second
Rectangle: Thirds: Third=Meta+Alt+PgUp,none,Rectangle: Thirds: Third
Rectangle: Two Thirds: Center=Meta+Alt+End,none,Rectangle: Two Thirds: Center
Rectangle: Two Thirds: First=Meta+Alt+Del,none,Rectangle: Two Thirds: First
Rectangle: Two Thirds: Second=Meta+Alt+PgDown,none,Rectangle: Two Thirds: Second
```

You could provide setups with basic configurations for macOS and PC, both as laptop and desktop (ie. with/without number pad).

Not sure how KWin handles conflicting shortcuts that were not introduced through its own set shortcut mechanism. Probably users have to find these themselves.

You would then need an installation script that
- clears `Rectangle: ` lines in `kglobalshortcutsrc`
- asks for the desired preset
- copies it into  `kglobalshortcutsrc`
- runs `grep 'Rect' <file>  | sed -E 's/[^=]+=(.*)/\1/'  | sort | uniq -d` to return multiple occurrences of shortcuts.

The settings pane would then only have to show a brief explanation and link(s) to the preset and script files.

Sorry if that's a bit confused -- am in a hurry today.

**Comment by acristoffers** [comment]
Not a good idea, as Plasma does not watch this file for changes and it also requires the user to take a lot of extra steps, including logging out and in again. I recommend creating the shortcuts you want and then using the Export functionality. We can include a set of exported-shortcuts in the repo.

**Comment by noyannus** [comment]
Exported shortcuts can't be set to a subset of Kwin settings only. But the export functionality makes it easier: 
Offer a file with only the Rectangle settings, together with a HowTo: 
1. User hast to export their own settings,
2. open the exported file,
3. copy the Rectangle settings into it,
4. save, and
5. import that file.
(not tested)

**Comment by acristoffers** [comment]
You can, just export all global kwin shortcuts, open the file in a text editor and remove everything not kwin-rectangle related, except, of course, the first line.

**Comment by acristoffers** [comment]
That's exactly my point: we can export the default and any other set of shortcuts (like yours numeric-based ones) and offer them in this repo, mentioning them in the README. Much cleaner than messing around with the config files.

**Comment by noyannus** [comment]
Ah, wasn't aware that one can import subsets.

**Comment by acristoffers** [comment]
The exported file is just a plain-text INI-like file. You can just delete everything not related to Rectangle (except the first line) and that's it.

**Comment by acristoffers** [comment]
If you send me your numeric-centric export I'll generate the default ones too and put both in the repository with instructions in the settings. You can just paste them in a code block here if you want.

**Comment by noyannus** [comment]
Will do. Need to explore the move and stretch first; currently I only use the fixed size/position. May take some time; urgent stuff came up.

**Comment by noyannus** [comment]
`Meta+Shift+Num+X` does not work here for `Stretch: Step:…`. 
`Meta+Shift+<somethingelse>` is OK, e.g., `Meta+Shift+Up` works. 

But as combination with `Shift` tend to be a little difficult to press, I'd leave it at the current workaround with `Meta+Ctrl+Alt+Num+X`, which is much easier.

Current settings:
```
[kwin][Global Shortcuts]
Rectangle: Center=Meta+Ctrl+Num+5
Rectangle: Fourth: (1) First=Meta+NumLock
Rectangle: Fourth: (2) Second=Meta+Num+/
Rectangle: Fourth: (3) Third=Meta+Num+*
Rectangle: Fourth: (4) Fourth=Meta+Num+-
Rectangle: Half: (1) Center (Horizontal)=Meta+Alt+Shift+Left
Rectangle: Half: (1) Center (Vertical)=Meta+Alt+Shift+Down
Rectangle: Half: (2) Left=Meta+Num+4
Rectangle: Half: (2) Right=Meta+Num+6
Rectangle: Half: (3) Bottom=Meta+Num+2
Rectangle: Half: (3) Top=Meta+Num+8
Rectangle: Maximize=Meta+Num+Enter
Rectangle: Maximize: Almost=Meta+Num+,
Rectangle: Maximize: Height=Meta+Alt+Shift+Up
Rectangle: Maximize: Width=Meta+Alt+Shift+Right
Rectangle: Move: (1) Bottom Left=Meta+Ctrl+Num+1
Rectangle: Move: (2) Bottom=Meta+Ctrl+Num+2
Rectangle: Move: (3) Bottom Right=Meta+Ctrl+Num+3
Rectangle: Move: (4) Left=Meta+Ctrl+Num+4
Rectangle: Move: (5) Right=Meta+Ctrl+Num+6
Rectangle: Move: (6) Top Left=Meta+Ctrl+Num+7
Rectangle: Move: (7) Top=Meta+Ctrl+Num+8
Rectangle: Move: (8) Top Right=Meta+Ctrl+Num+9
Rectangle: Ninth: (1) Top Left=Meta+Alt+Num+7
Rectangle: Ninth: (2) Top Center=Meta+Alt+Num+8
Rectangle: Ninth: (3) Top Right=Meta+Alt+Num+9
Rectangle: Ninth: (4) Middle Left=Meta+Alt+Num+4
Rectangle: Ninth: (5) Middle Center=Meta+Alt+Num+5
Rectangle: Ninth: (6) Middle Right=Meta+Alt+Num+6
Rectangle: Ninth: (7) Bottom Left=Meta+Alt+Num+1
Rectangle: Ninth: (8) Bottom Center=Meta+Alt+Num+2
Rectangle: Ninth: (9) Bottom Right=Meta+Alt+Num+3
Rectangle: Quarter: (1) Top Left=Meta+Num+7
Rectangle: Quarter: (2) Top Right=Meta+Num+9
Rectangle: Quarter: (3) Bottom Left=Meta+Num+1
Rectangle: Quarter: (4) Bottom Right=Meta+Num+3
Rectangle: Quarter: (5) Centered=Meta+Num+5
Rectangle: Sixth: (1) Top Left=Meta+Ins
Rectangle: Sixth: (2) Top Center=Meta+Home
Rectangle: Sixth: (3) Top Right=Meta+PgUp
Rectangle: Sixth: (4) Bottom Left=Meta+Del
Rectangle: Sixth: (5) Bottom Center=Meta+End
Rectangle: Sixth: (6) Bottom Right=Meta+PgDown
Rectangle: Stretch: (1) Bottom=Meta+Shift+Down
Rectangle: Stretch: (1) Top=Meta+Shift+Up
Rectangle: Stretch: (2) Left=Meta+Shift+Left
Rectangle: Stretch: (2) Right=Meta+Shift+Right
Rectangle: Stretch: Step: (1) Bottom Left=Meta+Ctrl+Alt+Num+1
Rectangle: Stretch: Step: (2) Bottom=Meta+Ctrl+Alt+Num+2
Rectangle: Stretch: Step: (3) Bottom Right=Meta+Ctrl+Alt+Num+3
Rectangle: Stretch: Step: (4) Left=Meta+Ctrl+Alt+Num+4
Rectangle: Stretch: Step: (5) Right=Meta+Ctrl+Alt+Num+6
Rectangle: Stretch: Step: (6) Top Left=Meta+Ctrl+Alt+Num+7
Rectangle: Stretch: Step: (7) Top=Meta+Ctrl+Alt+Num+8
Rectangle: Stretch: Step: (8) Top Right=Meta+Ctrl+Alt+Num+9
Rectangle: Third: (1) First=Meta+Alt+Ins
Rectangle: Third: (2) Second=Meta+Alt+Home
Rectangle: Third: (3) Third=Meta+Alt+PgUp
Rectangle: Two Thirds: (1) Left=Meta+Alt+Del
Rectangle: Two Thirds: (2) Center=Meta+Alt+End
Rectangle: Two Thirds: (3) Right=Meta+Alt+PgDown
```

The logic behind it is this (still with `Shift` for `Step:`); open in spreadsheet:
[Rectangle Keys.csv](https://github.com/acristoffers/kwin-rectangle/files/11353255/Rectangle.Keys.csv) -- You could use it to build a naming scheme, if you want. 

For the pesky NumLock, maybe you could ask in the Readme if someone knows a trick to intercept NumLock, or to make numpad's `   =   ` `   (   ` `   )   ` ` backsp` work with `Meta`.

**Comment by acristoffers** [comment]
I've added both to the repo and updated the readme. I have the impression I said it already, but maybe I just thought about it but never wrote it: shortcuts are handled by plasma, not by the script. There's nothing a script can do in that regard. I'm not sure if it's KGlobalAccel or KWin who handles the shortcuts, but one way or another, if you cannot set them in System Settings, then it is not possible, and any fix for that has to be done in the right project. At least in Wayland it makes sense that KWin handles that, but in Xorg it could be handled by a separated process like KGlobalAccel.

**Comment by noyannus** [comment]
Well then, it's fairly good already. With the big keyboard it's really easy to flick the windows around!
