### ISSUE TITLE
Naming shortcuts

### ISSUE THREAD

**Issue by noyannus** [acristoffers/kwin-rectangle#11]
The system settings for Kwin don't allow sorting by shortcuts (let alone by modifiers or by non-modifiers only), only by names of actions. 

With so many options now, it's a long list, and alphabetic sort is not the best here. I'd like therefore to suggest a naming scheme that introduces more levels of categorizing, and uses numbering to sort by effect or keyboard key). Having the long list in logical instead of alphabetical order makes a lower cognitive load.

```
Maximize:    # here, alphabet sorting works well and its only a few entries anyway
	Almost
	Full
	Only [up, down, to left, to right])  # this is not implemented
Minimize
Move:    # name by numpad key position to avoid alphabet sorting and have left–middle–right order 
	1. Bottom left
	2. Bottom
	3. Bottom right
	4. ...
	9. Top right
Size & Position:    # number by screen division; could include Maxi/Mini as "1a. Maximize", "1b. Minimize"
	2. Halves:
		Left
		Right
		...
	3a. Thirds:
	3b. Two-Thirds:
	...
	9. Ninths
```

I understand if that is too much hassle for the not so frequent activity of setting settings. In that case, some renames would sort entries together and make them easier to find: "Center:" as "Move: Center:" would sort it with other moves, similarly "Almost Maximized" as "Maximized: Almost", and "Centered Quarter" as "Quarter: Centered".

**Comment by acristoffers** [comment]
I'll see if I can better group the shorcuts. Your examples make sense.

**Comment by noyannus** [comment]
Cool!
