### ISSUE TITLE
[Enhancement] Three-Fourths?

### ISSUE THREAD

**Issue by noyannus** [acristoffers/kwin-rectangle#13]
Can we have three-fourth sized portrait mode windows? Very useful to have a folder tree or file list in one fourth and an application in the remaining space. Similar to the folder trees integrated in some applications.

**Comment by acristoffers** [comment]
Instead I'll give you for "Stretch" commands that makes the border of the window "touch" the border of the screen as well as "Stretch: Step" commands that increases the span of rows/cols. This way you can get similar effects with all supported sizes. I found it to be more versatile than to have a separate shortcut for every possible size combo.

**Comment by acristoffers** [comment]
Works for me. Are you using the sixths to test? The effect won't be visible on quarter, for example.

Start:

|-|-|-|
|---|---|---|
|X|-|-|
|-|-|-|

After Step: Right:

|-|-|-|
|---|---|---|
|X|X|-|
|-|-|-|

If you now call Step: Bottom:

|-|-|-|
|---|---|---|
|X|X|-|
|X|X|-|

**Comment by noyannus** [comment]
My error.  I tested beginning with the center ninth and for some reason was expecting smaller steps, like e.g. 10% of screen width. And of course, with a step size of 1 row/col, it must look exactly like maximizing to one side. Sorry for the confusion.
