### ISSUE TITLE
kFind does not react to kwin-rectangle

### ISSUE THREAD

**Issue by noyannus** [acristoffers/kwin-rectangle#15]
kFind does not react to kwin-rectangle, but it does to the usual shortcuts `meta + left`, `meta + right`, etc.

**Comment by acristoffers** [comment]
I cannot reproduce, it works for me.

**Comment by noyannus** [comment]
Maybe others have more observations? 

For the record:
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.1.23-1-MANJARO (64-bit)
Graphics Platform: X11

**Comment by acristoffers** [comment]
Oh, mine was Wayland. I'll try in X11 to see if that's it.

**Comment by acristoffers** [comment]
Yep, that was it. Wayland does not set roles for windows like X11 does, so my filtering does not work here. Which makes me ask myself why have the filter in first place? Why not just let the user do whatever? It may not work properly on some dialogues, but then the user will see there's a problem, right? Also, why isn't kFind just a normal window? That also seems wrong... I'll just remove the restrictions from kwin-rectangle in the next release.

**Comment by noyannus** [comment]
Now it works. Works also on the system tray popup. Nice. 
Was a reboot necessary instead of a mere logout-login? Never mind.
