### ISSUE TITLE
Window flickering when resizing after using rectangle 

### ISSUE THREAD

**Issue by mcaceresb** [acristoffers/kwin-rectangle#19]
- Use a rectangle shortcut to place a window
- Resize the window
- It often flickers briefly to show the window in its position before it was placed via a rectangle shortcut

Here is a demo, showing I can resize normally without issue, I can use rectangle without issue, but then I try to resize and get the flickering:

[resizing-after-rectangle.webm](https://github.com/acristoffers/kwin-rectangle/assets/4219197/67de1809-3c06-4b3f-a702-487c42af2113)

kwin rectangle 1.2.8, plasma 5.27.8

**Comment by acristoffers** [comment]
Thanks for the bug report.

I have a guess as for why, but will only be able to test on the weekend. It seems that I have to copy the current position of the window before restoring the geometry, otherwise it resets to `(0,0)`, which is the reason why it briefly appears on the top-left corner.

**Comment by acristoffers** [comment]
This latest commit should fix the issue. I'll make a new release in the KDE store that should be available soon. Can you update (when it appears to you) and confirm that the issue was solved?

**Comment by acristoffers** [comment]
It was possible to distinguish move from resize, so I made it so resizing only clears the window's memory of its last geometry. Version 1.2.10 was already uploaded to the store and should (hopefully) fully fix this issue now. Could you please verify again and see if it's alright on your machine?

**Comment by mcaceresb** [comment]
@acristoffers Seems to work! Thanks.
