### ISSUE TITLE
Script doesn't resize windows (Wayland).

### ISSUE THREAD

**Issue by Sojiro84** [acristoffers/kwin-rectangle#2]
So, in a VM with x11 it works.

This script seems perfect for my needs since I can position windows to places together with sexy gapps.

My real machine run Wayland and has 3 monitors and the most left is a vertical one.

When I use any of the shortcuts, the window is moved to the correct starting pixel (for example, on my vertical monitor, going to the top-left or maximizing to the top part of the screen) places it at the correct x,y but it doesn't resize the window.

What can I do to provide you with useful info?

**Comment by Sojiro84** [comment]
Edit: just noticed that when I want to center a window, it places it between my vertical monitor and the middle monitor and at the middle near the top of the screen.

**Comment by acristoffers** [comment]
Seems like the functions I use give me the dimensions of the desktop across monitors. Is that an extended desktop you have, or does every monitor have its own separated desktop? I would have to search on the API to see what my options on getting the desktop's measurements are. If you know of any kwin plugin that works on your setup, point me to it so I can see how it is getting the dimensions.

**Comment by Sojiro84** [comment]
In the past I used https://github.com/esjeon/krohnkite which was able to do it's tiling. Although that script has yet to implement vertical monitor support (but it did still tile windows on the vertical monitor, just not while accounting for a vertical ratio).

For centering I currently still use: https://github.com/KSmanis/kwin-move-window-to-center

**Comment by acristoffers** [comment]
Can you please test if it's now working? There seems to be an inconsistency in kwin's API between X and Wayland, I think it now works on both.

**Comment by Sojiro84** [comment]
Works perfectly! I can resize properly now and the centering works correctly as well across monitors!

Thanks!
