### ISSUE TITLE
Enhancement Request: Consider Floating Panel Positioning

### ISSUE THREAD

**Issue by Sojiro84** [acristoffers/kwin-rectangle#22]
Hello,

Currently, the script calculates window positions based on the entire screen area, which sometimes results in unintended docking of floating panels when windows are positioned near the bottom of the screen.

I would like to request a feature that takes into account the presence of floating panels when positioning windows.

I like the new floating panel option of Plasma 6, but since your script doesn't take that into account, my panel remains docked.

Thanks for reading.

**Comment by Sojiro84** [comment]
I recently experimented with ChatGPT's code suggestion, and it appears to function as intended:

```
function screenSize() {
    const panelHeight = 44 /* height of your floating panel */;
    const screen = workspace.clientArea(
        KWin.PlacementArea,
        workspace.activeScreen,
        workspace.currentDesktop
    );
    screen.height -= panelHeight; // Adjusting for the floating panel
    return screen;
}
```
However, I encountered an unexpected behavior with Plasma 6 regarding the floating panel. Unlike Plasma 5, where the floating panel remained unaffected, Plasma 6 automatically docks the panel when a window approaches. To counter this behavior, I adjusted the panel height to 44 pixels, even though my panel is actually 36 pixels high.

It seems Plasma defaults to a calculation assuming a panel height of 44 pixels.

**Comment by acristoffers** [comment]
Thank you for your issue :)

There is no option, unfortunately, to prevent the floating panel from docking. The option to make windows go below it also makes the function `clientArea` report the full height of the desktop, so I cannot know the size that will make the panel not dock. For this reason, I added 4 properties to settings page that allows the user to set margins to the desktop. It's a bit of manual work, but fixes the issue no matter how many panels you have or where they are placed.
