### ISSUE TITLE
Sometimes window is in task bar of wrong screen

### ISSUE THREAD

**Issue by noyannus** [acristoffers/kwin-rectangle#24]
A window that has been resized/positioned with Kwin Rectangle does not always appear in the task manager of the pane of the screen that window is on. 

Example observed on a two-screen setup (setting in image below):

Window is resized/moved into right *half* of the left screen (primary); it is represented in the task bar of the *left* screen (here cut off for image size reduction).

![Screenshot_20240409_123454](https://github.com/acristoffers/kwin-rectangle/assets/6339921/53b1d317-8e25-4e6e-ba6a-17398c401e03)

Same window resized/moved into right *third* of the left screen; it is represented in the task bar of the *right" screen.

![Screenshot_20240409_123525](https://github.com/acristoffers/kwin-rectangle/assets/6339921/46d4b0b7-217a-4675-9449-83cc7282c7fb)

Screen setup:

![image](https://github.com/acristoffers/kwin-rectangle/assets/6339921/f0ef2d5d-18ca-4de4-ad57-2e18d59dcf58)

Edit: 
The system is:
Operating System: openSUSE Tumbleweed 20240407
KDE Plasma Version: 6.0.3
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.3
Kernel Version: 6.8.4-rc1-1-default (64-bit)
Graphics Platform: X11

**Comment by acristoffers** [comment]
I believe this should be reported to KDE, as I don't have control over the taskbar. The only thing I do is change the window geometry, the way the taskbar maps window location to screen is not controllable by the extension.

**Comment by noyannus** [comment]
Ah, I see. 
Thanks.
