### ISSUE TITLE
Problem with KDE upper panel

### ISSUE THREAD

**Issue by Alfatango12** [acristoffers/kwin-rectangle#3]
Hi, I really like this script but I discovered a problem. In my KDE customization I've put the panel at the top of the screen but when I position a program using a shortcut of the script, the title bar of the program goes under the panel and at the bottom there is a unused space. Here's a demonstration:
Thank you very much!

https://user-images.githubusercontent.com/89928318/131702592-9d70bdae-9fde-42cf-af8b-d06beadcd970.mp4

:

**Comment by acristoffers** [comment]
I'll take a look at it. Seems like I get the right sizes, but I need to apply offsets for possible panels when moving... I'm pulling my hair out at work at the moment, so I might be able to take a look only the next weekend. :/
