### ISSUE TITLE
How can we set inner (ip) and outer (op) padding? (Plasma 5.27)

### ISSUE THREAD

**Issue by brendon-at-rea** [acristoffers/kwin-rectangle#8]
Hi again, I can see [code for a configurable padding amount](https://github.com/acristoffers/kwin-rectangle/blob/a0dfd751703dbcf4546ebd784aac772067505f51/contents/ui/config.ui#L36) but I don't see anywhere in the System Settings to adjust these values.

![Screenshot_20230324_112401](https://user-images.githubusercontent.com/96089213/227392798-bce52605-9f14-43c5-92ae-88ee5770a0a1.jpeg)

I'm on Neon (Plasma 5.27) - I wonder if something has changed to stop the Config dialog becoming available?

Thanks for your help on my previous issue BTW.

**Comment by acristoffers** [comment]
Hi,

this is a known issue and probably a Plasma bug. For the config button to appear, a symlink needs to exist, but when you install using the Get Addons window it never gets created.

You can manually copy the file kwin-rectangle.desktop to /usr/share/kservices5/kwin-rectangle.desktop to get the button to appear (you may have to log out and in again, I'm not sure). I see that KZones has its symlink created without problems, so I'll see if they do anything different from me to get their desktop file automatically linked.

**Comment by acristoffers** [comment]
Voilà, it seems the problem is solved. I changed the metadata file to reflect some entries in KZones and now the icon appears even without creating the symlink. Can you update and see if it is working properly? Delete the symlink if you created it. And thanks again for reporting issues!

**Comment by brendon-at-rea** [comment]
Hi @acristoffers , thank you again for your help!

Unfortunately, updating to the latest hasn't helped:

![Screenshot_20230327_151459](https://user-images.githubusercontent.com/96089213/227839386-71b8d7c1-0851-4e2f-9a7c-555f78afa022.jpeg)

I also can't find a file `kwin-rectangle.desktop` anywhere in this repo. I do have this file: `~/.local/share/kwin/scripts/kwin-rectangle/kwin-rectangle.kwinscript`

So, I'm probably doing something boneheaded!   I'll keep poking around to see what I can find.

**Comment by acristoffers** [comment]
Can you try uninstalling and reinstalling? Shouldn't make a difference, but who knows, may be worth the shot.

**Comment by brendon-at-rea** [comment]
Me again, I was able to fix this by adding to metadata.json. 
https://develop.kde.org/docs/plasma/kwin/#configuration

I'll submit a PR.
